<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'eccuenta',
'ec_nomelemento',
'ec_codelem',
'ecunidad',
'nicsp_cuentacostonew',
'nicsp_cuentacostonewc',
'nicsp_cuentacostonewn',
'nicsp_cuentacostoservicio',
'nicsp_cuentacostoservicioc',
'nicsp_cuentacostoservicion' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'eccuenta' => array( 'integrated_edit_field4' ),
'ec_nomelemento' => array( 'integrated_edit_field3' ),
'ec_codelem' => array( 'integrated_edit_field' ),
'ecunidad' => array( 'integrated_edit_field6' ),
'nicsp_cuentacostonew' => array( 'integrated_edit_field1' ),
'nicsp_cuentacostonewc' => array( 'integrated_edit_field2' ),
'nicsp_cuentacostonewn' => array( 'integrated_edit_field5' ),
'nicsp_cuentacostoservicio' => array( 'integrated_edit_field7' ),
'nicsp_cuentacostoservicioc' => array( 'integrated_edit_field8' ),
'nicsp_cuentacostoservicion' => array( 'integrated_edit_field9' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'top' => array( 'view_header' ),
'grid' => array( 'integrated_edit_field4',
'integrated_edit_field',
'integrated_edit_field6',
'text',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field5',
'integrated_edit_field3',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'text1' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'view_header' => 'top',
'integrated_edit_field4' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field6' => 'grid',
'text' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field9' => 'grid',
'text1' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'text' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'text1' => array( 'location' => 'grid',
'cellId' => 'c16' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field4',
'integrated_edit_field3',
'integrated_edit_field',
'integrated_edit_field6',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ),
'text' => array( 'text',
'text1' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'text1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c6' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ) ) ) ),
'cells' => array( 'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ) ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'text' ),
'bold' => true,
'background' => '#f7f7f7' ),
'c7' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3' ),
'useFullWidth' => true ),
'c11' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field9' ) ),
'c16' => array( 'model' => 'c3',
'items' => array( 'text1' ),
'bold' => true,
'background' => '#f7f7f7' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field4' => array( 'field' => 'eccuenta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'ec_nomelemento',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'ec_codelem',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'ecunidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'nicsp_cuentacostonew',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'nicsp_cuentacostonew',
'table' => 'alelemconsumo_consulta',
'type' => 3 ) ),
'integrated_edit_field2' => array( 'field' => 'nicsp_cuentacostonewc',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'nicsp_cuentacostonewc',
'table' => 'alelemconsumo_consulta',
'type' => 3 ) ),
'integrated_edit_field5' => array( 'field' => 'nicsp_cuentacostonewn',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'nicsp_cuentacostonewn',
'table' => 'alelemconsumo_consulta',
'type' => 3 ) ),
'integrated_edit_field7' => array( 'field' => 'nicsp_cuentacostoservicio',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'nicsp_cuentacostoservicio',
'table' => 'alelemconsumo_consulta',
'type' => 3 ) ),
'integrated_edit_field8' => array( 'field' => 'nicsp_cuentacostoservicioc',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'nicsp_cuentacostoservicioc',
'table' => 'alelemconsumo_consulta',
'type' => 3 ) ),
'integrated_edit_field9' => array( 'field' => 'nicsp_cuentacostoservicion',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'nicsp_cuentacostoservicion',
'table' => 'alelemconsumo_consulta',
'type' => 3 ) ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<p>Cuenta contable | Nuevos</p>',
'type' => 0 ),
'editedByRte' => true,
'bold' => true,
'font-family' => 'Roboto',
'font-size' => '18px' ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => '<p>Cuenta contable | En servicio</p>',
'type' => 0 ),
'editedByRte' => true,
'font-family' => 'Roboto',
'bold' => true,
'font-size' => '18px' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>