<?php
			$optionsArray = array( 'totals' => array( 'almovconsdia_id_fk' => array( 'totalsType' => '' ),
'almovconsdiae_cantidad' => array( 'totalsType' => '' ),
'almovconsdiae_id' => array( 'totalsType' => '' ),
'consumo_id_fk' => array( 'totalsType' => '' ),
'ctrl_saldo' => array( 'totalsType' => '' ),
'mcd_valmovto' => array( 'totalsType' => '' ),
'mcd_valunitant' => array( 'totalsType' => '' ),
'mcdalmacen' => array( 'totalsType' => '' ),
'mcdcodelem' => array( 'totalsType' => '' ),
'mcdcuenta' => array( 'totalsType' => '' ),
'mcdnomelem' => array( 'totalsType' => '' ),
'sys_doclasedoc_id_fk' => array( 'totalsType' => '' ),
'sys_document_func' => array( 'totalsType' => '' ),
'sys_fecha' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'sys_time' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'almovconsdiae_id',
'almovconsdia_id_fk',
'almovconsdiae_cantidad',
'sys_user',
'ctrl_saldo',
'sys_document_func',
'sys_doclasedoc_id_fk',
'mcdalmacen',
'mcdcuenta',
'mcdcodelem',
'mcdnomelem',
'consumo_id_fk',
'mcd_valunitant',
'mcd_valmovto' ),
'exportFields' => array( 'almovconsdiae_id',
'almovconsdia_id_fk',
'almovconsdiae_cantidad',
'sys_user',
'sys_document_func',
'sys_doclasedoc_id_fk',
'mcdalmacen',
'mcdcuenta',
'mcdcodelem',
'mcdnomelem',
'consumo_id_fk',
'ctrl_saldo',
'mcd_valunitant',
'mcd_valmovto' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'almovconsdiae_id' => array( 'export_field' ),
'almovconsdia_id_fk' => array( 'export_field1' ),
'almovconsdiae_cantidad' => array( 'export_field2' ),
'sys_user' => array( 'export_field3' ),
'ctrl_saldo' => array( 'export_field4' ),
'sys_document_func' => array( 'export_field7' ),
'sys_doclasedoc_id_fk' => array( 'export_field8' ),
'mcdalmacen' => array( 'export_field9' ),
'mcdcuenta' => array( 'export_field10' ),
'mcdcodelem' => array( 'export_field11' ),
'mcdnomelem' => array( 'export_field12' ),
'consumo_id_fk' => array( 'export_field13' ),
'mcd_valunitant' => array( 'export_field5' ),
'mcd_valmovto' => array( 'export_field6' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field4',
'export_field5',
'export_field6' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field5',
'export_field6' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field4',
'export_field5',
'export_field6' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'almovconsdiae_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'almovconsdia_id_fk',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'almovconsdiae_cantidad',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'ctrl_saldo',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'sys_document_func',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'sys_doclasedoc_id_fk',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'mcdalmacen',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'mcdcuenta',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'mcdcodelem',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'mcdnomelem',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'consumo_id_fk',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'mcd_valunitant',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'mcd_valmovto',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>