<?php
			$optionsArray = array( 'master' => array( 'gedocumentos_egresos_consumo' => array( 'preview' => true ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'almovconsdia_id_fk',
'almovconsdiae_cantidad',
'sys_user',
'ctrl_saldo',
'sys_document_func',
'sys_doclasedoc_id_fk',
'mcdalmacen',
'mcdcuenta',
'mcdcodelem',
'mcdnomelem',
'consumo_id_fk',
'mcd_valunitant' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'almovconsdia_id_fk' => array( 'integrated_edit_field' ),
'almovconsdiae_cantidad' => array( 'integrated_edit_field1' ),
'sys_user' => array( 'integrated_edit_field2' ),
'ctrl_saldo' => array( 'integrated_edit_field3' ),
'sys_document_func' => array( 'integrated_edit_field6' ),
'sys_doclasedoc_id_fk' => array( 'integrated_edit_field7' ),
'mcdalmacen' => array( 'integrated_edit_field8' ),
'mcdcuenta' => array( 'integrated_edit_field9' ),
'mcdcodelem' => array( 'integrated_edit_field10' ),
'mcdnomelem' => array( 'integrated_edit_field11' ),
'consumo_id_fk' => array( 'integrated_edit_field12' ),
'mcd_valunitant' => array( 'integrated_edit_field4' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'edit_header' ),
'grid' => array( 'master_info',
'integrated_edit_field',
'integrated_edit_field11',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field1',
'integrated_edit_field3',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field12',
'integrated_edit_field8',
'integrated_edit_field4',
'integrated_edit_field2' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'edit_header' => 'top',
'master_info' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field2' => 'grid' ),
'itemLocations' => array( 'master_info' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c17' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field4' ),
'master_info' => array( 'master_info' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 3 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ),
array( 'cell' => 'c18' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c19' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c20' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c23' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c24' ),
array( 'cell' => 'c25' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'master_info' ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ) ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field11' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field9' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3' ) ),
'c16' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7' ) ),
'c17' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ),
'c18' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field12' ) ),
'c19' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ) ),
'c20' => array( 'model' => 'c3',
'items' => array(  ) ),
'c23' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ) ),
'c24' => array( 'model' => 'c3',
'items' => array(  ) ),
'c25' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field' => array( 'field' => 'almovconsdia_id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field1' => array( 'field' => 'almovconsdiae_cantidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'ctrl_saldo',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'ctrl_saldo',
'table' => 'almovconsdia_egresos',
'type' => 3 ),
'background' => '#f7f7f7',
'color' => '#36077a',
'mobileDisplay' => '',
'font-family' => 'Roboto' ),
'integrated_edit_field6' => array( 'field' => 'sys_document_func',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'sys_document_func',
'table' => 'almovconsdia_egresos',
'type' => 3 ) ),
'integrated_edit_field7' => array( 'field' => 'sys_doclasedoc_id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'sys_doclasedoc_id_fk',
'table' => 'almovconsdia_egresos',
'type' => 3 ) ),
'integrated_edit_field8' => array( 'field' => 'mcdalmacen',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'mcdalmacen',
'table' => 'almovconsdia_egresos',
'type' => 3 ),
'updateOnEdit' => false ),
'integrated_edit_field9' => array( 'field' => 'mcdcuenta',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'mcdcuenta',
'table' => 'almovconsdia_egresos',
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 'mcdcodelem',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'mcdcodelem',
'table' => 'almovconsdia_egresos',
'type' => 3 ) ),
'integrated_edit_field11' => array( 'field' => 'mcdnomelem',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'mcdnomelem',
'table' => 'almovconsdia_egresos',
'type' => 3 ),
'updateOnEdit' => false ),
'integrated_edit_field12' => array( 'field' => 'consumo_id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'consumo_id_fk',
'table' => 'almovconsdia_egresos',
'type' => 3 ) ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'gedocumentos_egresos_consumo' => 'true' ) ),
'integrated_edit_field4' => array( 'field' => 'mcd_valunitant',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>