<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'username_button' ),
'top' => array(  ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'dashboard-item' => 'grid',
'dashboard-item1' => 'grid',
'dashboard-item2' => 'grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'username_button' => 'supertop' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'global_users',
'dashType' => 7,
'dashName' => 'global_users_snippet',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => 'barcode' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'Dashboard_snippet',
'headerBg' => '#FFFFFF',
'headerColor' => '#d4e717',
'bodyBg' => '#229954',
'bodyColor' => '#FFFFFF',
'panelBorder' => '2px',
'borderColor' => '#229954',
'snippetStyle' => 'right',
'iconBg' => '#ffffff',
'iconColor' => '#1f1e23',
'tabLeaveSpace' => true ),
'elementName' => 'global_users_snippet',
'table' => 'global_users',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'Dashboard_snippet',
'masterTable' => '',
'tabLocation' => 'above',
'tabLeaveSpace' => true,
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'global_users',
'dashType' => 7,
'dashName' => 'global_users_snippet1',
'bsStyle' => 'warning',
'panelType' => 1,
'icon' => array( 'fa' => 'building' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'Dashboard_snippet1',
'headerBg' => '',
'headerColor' => '#2e1be4',
'bodyBg' => '#c8bc32',
'bodyColor' => '#ffffff',
'panelBorder' => '2px',
'borderColor' => '#9b9122',
'snippetStyle' => 'right',
'iconColor' => '#000000' ),
'elementName' => 'global_users_snippet1',
'table' => 'global_users',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'Dashboard_snippet1',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'warning' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'global_users',
'dashType' => 7,
'dashName' => 'global_users_snippet2',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'star' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'Dashboard_snippet2',
'snippetStyle' => 'right',
'headerColor' => '#ffffff',
'bodyBg' => '#cccccc',
'bodyColor' => '#000000',
'iconColor' => '#000000',
'panelBorder' => '2px',
'borderColor' => '' ),
'elementName' => 'global_users_snippet2',
'table' => 'global_users',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'Dashboard_snippet2',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'global_users_idusrglobal' => array( array( 'field' => 'idusrglobal',
'table' => 'global_users' ) ),
'global_users_Username' => array( array( 'field' => 'Username',
'table' => 'global_users' ) ),
'global_users_usr_nombresfull' => array( array( 'field' => 'usr_nombresfull',
'table' => 'global_users' ) ),
'global_users_usr_personalid' => array( array( 'field' => 'usr_personalid',
'table' => 'global_users' ) ),
'global_users_Password' => array( array( 'field' => 'Password',
'table' => 'global_users' ) ),
'global_users_usr_email' => array( array( 'field' => 'usr_email',
'table' => 'global_users' ) ),
'global_users_global_rol' => array( array( 'field' => 'global_rol',
'table' => 'global_users' ) ),
'global_users_active' => array( array( 'field' => 'active',
'table' => 'global_users' ) ) ),
'allSearchFields' => array( 'global_users_idusrglobal',
'global_users_Username',
'global_users_usr_nombresfull',
'global_users_usr_personalid',
'global_users_Password',
'global_users_usr_email',
'global_users_global_rol',
'global_users_active' ),
'googleLikeFields' => array( 'global_users_idusrglobal',
'global_users_Username',
'global_users_usr_nombresfull',
'global_users_usr_personalid',
'global_users_Password',
'global_users_usr_email',
'global_users_global_rol',
'global_users_active' ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c4' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1' ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'global_users',
'dashType' => 7,
'dashName' => 'global_users_snippet',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => 'barcode' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'Dashboard_snippet',
'headerBg' => '#FFFFFF',
'headerColor' => '#d4e717',
'bodyBg' => '#229954',
'bodyColor' => '#FFFFFF',
'panelBorder' => '2px',
'borderColor' => '#229954',
'snippetStyle' => 'right',
'iconBg' => '#ffffff',
'iconColor' => '#1f1e23',
'tabLeaveSpace' => true ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'global_users',
'dashType' => 7,
'dashName' => 'global_users_snippet1',
'bsStyle' => 'warning',
'panelType' => 1,
'icon' => array( 'fa' => 'building' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'Dashboard_snippet1',
'headerBg' => '',
'headerColor' => '#2e1be4',
'bodyBg' => '#c8bc32',
'bodyColor' => '#ffffff',
'panelBorder' => '2px',
'borderColor' => '#9b9122',
'snippetStyle' => 'right',
'iconColor' => '#000000' ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'global_users',
'dashType' => 7,
'dashName' => 'global_users_snippet2',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'star' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'Dashboard_snippet2',
'snippetStyle' => 'right',
'headerColor' => '#ffffff',
'bodyBg' => '#cccccc',
'bodyColor' => '#000000',
'iconColor' => '#000000',
'panelBorder' => '2px',
'borderColor' => '' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>